language: java
jdk: oraclejdk17

addons:
  postgresql: '13'
  apt:
    update: true
    packages:
      - postgresql-13
      - postgresql-client-13

services:
  - postgresql

before_script:
  - sudo psql -p 5432 -U postgres -c 'create database shop;'