language: java
jdk: oraclejdk17

addons:
  postgresql: '13'
  apt:
    update: true
    packages:
      - postgresql-13
      - postgresql-client-13

services:
  - postgresql

env:
  global:
    - PGPORT=5433
  jobs:
    - NODE_ENV=test DB_PORT=5433 DB_USERNAME=postgres

before_install:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  - sudo service postgresql@13-main restart

before_script:
  - sudo psql -p 5433 -U postgres -c 'create database shop;'

deploy:
  provider: heroku
  api_key:
    secure: "04045f75-a87c-429c-be59-7f9e2ccfe650"
  app: fierce-journey-45235
  on:
    branch: main